- name: update all packages to the latest version
  apt:
    name: '*'
    state: latest
    update_cache: yes

- name: upgrade all packages to the latest version
  apt:
    upgrade: dist

- name: install dependent packages
  apt:
    name: '{{ packages }}'
  vars:
    packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common

- name: add apt-key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg

- name: add repo
  apt_repository:
    repo: deb [arch=armhf] https://download.docker.com/linux/raspbian stretch stable
    state: present

- name: update all packages to the latest version
  apt:
    name: '*'
    state: latest
    update_cache: yes

- name: install docker-ce
  apt:
    name: docker-ce

- name: add install user to docker group 
  user:
    name: '{{ ansible_user }}'
    groups: docker
    append: yes

